name       : opusfile
version    : '0.12'
release    : 7
source     :
    - https://github.com/xiph/opusfile/releases/download/v0.12/opusfile-0.12.tar.gz : 118d8601c12dd6a44f52423e68ca9083cc9f2bfe72da7a8c1acb22a80ae3550b
license    : BSD-3-Clause
component  : programming.library
summary    : Library for opening, seeking, and decoding .opus files
description: |
    The opusfile and opusurl libraries provide a high-level API for decoding and seeking within .opus files on disk or over http(s).
emul32     : yes
builddeps  :
    - pkgconfig32(ogg)
    - pkgconfig32(opus)
    - openssl-11-32bit-devel # Use until transition is complete
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rvf $installdir/usr/share/