name       : opusfile
version    : 0.11
release    : 5
source     :
    - https://archive.mozilla.org/pub/opus/opusfile-0.11.tar.gz : 74ce9b6cf4da103133e7b5c95df810ceb7195471e1162ed57af415fabf5603bf
license    : BSD-3-Clause
component  : programming.library
summary    : Library for opening, seeking, and decoding .opus files
description: |
    The opusfile and opusurl libraries provide a high-level API for decoding and seeking within .opus files on disk or over http(s).
emul32     : yes
builddeps  :
    - pkgconfig32(ogg)
    - pkgconfig32(openssl)
    - pkgconfig32(opus)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
