name       : opusfile
version    : 0.8
release    : 2
source     :
    - https://archive.mozilla.org/pub/opus/opusfile-0.8.tar.gz : 2c231ed3cfaa1b3173f52d740e5bbd77d51b9dfecb87014b404917fba4b855a4
license    : BSD-3-Clause
component  : programming
summary    : Library for opening, seeking, and decoding .opus files
description: |
    The opusfile and opusurl libraries provide a high-level API for decoding and 
    seeking within .opus files on disk or over http(s).
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(ogg)
    - pkgconfig(opus)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
