name       : opusfile
version    : 0.7
release    : 1
source     :
    - https://archive.mozilla.org/pub/opus/opusfile-0.7.tar.gz : 9e2bed13bc729058591a0f1cab2505e8cfd8e7ac460bf10a78bcc3b125e7c301
license    : BSD-3-Clause
summary    : Library for opening, seeking, and decoding .opus files
description: |
    Library for opening, seeking, and decoding .opus files
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(ogg)
    - pkgconfig(opus)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
